# Generated by Django 3.2.18 on 2023-04-11 13:04

import BK.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BK', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dentist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='booking',
            name='dentist',
            field=models.ForeignKey(default=BK.models.get_default_dentist, on_delete=django.db.models.deletion.CASCADE, to='BK.dentist'),
        ),
    ]
